// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LeagueCreate = {
    name: string;
    description?: (string | null);
};

export type LeaguePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type LeaguesPublic = {
    data: Array<LeaguePublic>;
    count: number;
};

export type LeagueUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SeasonCreate = {
    name: string;
    description?: (string | null);
    league_id: string;
};

export type SeasonPublic = {
    name: string;
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    league_id: string;
    id: string;
};

export type SeasonsPublic = {
    data: Array<SeasonPublic>;
    count: number;
};

export type SeasonUpdate = {
    name?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LeaguesReadLeaguesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type LeaguesReadLeaguesResponse = (LeaguesPublic);

export type LeaguesCreateLeagueData = {
    requestBody: LeagueCreate;
};

export type LeaguesCreateLeagueResponse = (LeaguePublic);

export type LeaguesReadLeagueData = {
    id: string;
};

export type LeaguesReadLeagueResponse = (LeaguePublic);

export type LeaguesUpdateLeagueData = {
    id: string;
    requestBody: LeagueUpdate;
};

export type LeaguesUpdateLeagueResponse = (LeaguePublic);

export type LeaguesDeleteLeagueData = {
    id: string;
};

export type LeaguesDeleteLeagueResponse = (Message);

export type LeaguesBulkDeleteLeaguesData = {
    requestBody: Array<(string)>;
};

export type LeaguesBulkDeleteLeaguesResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SeasonsReadSeasonsData = {
    leagueId?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type SeasonsReadSeasonsResponse = (SeasonsPublic);

export type SeasonsCreateSeasonData = {
    requestBody: SeasonCreate;
};

export type SeasonsCreateSeasonResponse = (SeasonPublic);

export type SeasonsUpdateSeasonData = {
    id: string;
    requestBody: SeasonUpdate;
};

export type SeasonsUpdateSeasonResponse = (SeasonPublic);

export type SeasonsDeleteSeasonData = {
    id: string;
};

export type SeasonsDeleteSeasonResponse = (Message);

export type SeasonsEndSeasonData = {
    id: string;
};

export type SeasonsEndSeasonResponse = (SeasonPublic);

export type SeasonsBulkDeleteSeasonsData = {
    requestBody: Array<(string)>;
};

export type SeasonsBulkDeleteSeasonsResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);