// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClubCreate = {
    name: string;
    logo?: (string | null);
    ea_id?: (string | null);
};

export type ClubPublic = {
    name: string;
    logo?: (string | null);
    ea_id?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type ClubsPublic = {
    data: Array<ClubPublic>;
    count: number;
};

export type ClubUpdate = {
    name?: (string | null);
    logo?: (string | null);
    ea_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LeagueCreate = {
    name: string;
    description?: (string | null);
};

export type LeaguePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type LeaguesPublic = {
    data: Array<LeaguePublic>;
    count: number;
};

export type LeagueUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type MatchesPublic = {
    data: Array<MatchPublic>;
    count: number;
};

export type MatchPublic = {
    match_id: string;
    league_id: string;
    season_id: string;
    raw_data?: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type MatchUpdate = {
    raw_data: {
        [key: string]: unknown;
    };
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SchedulerCreate = {
    league_id: string;
    season_id: string;
    days?: Array<(string)>;
    start_time: string;
    end_time: string;
    interval_minutes?: number;
    is_enabled?: boolean;
};

export type SchedulerPublic = {
    league_id: string;
    season_id: string;
    days?: Array<(string)>;
    start_time: string;
    end_time: string;
    interval_minutes?: number;
    is_enabled?: boolean;
    id: string;
    last_run_at?: (string | null);
    league_name: string;
    season_name: string;
};

export type SchedulersPublic = {
    data: Array<SchedulerPublic>;
    count: number;
};

export type SchedulerUpdate = {
    days?: (Array<(string)> | null);
    start_time?: (string | null);
    end_time?: (string | null);
    interval_minutes?: (number | null);
    is_enabled?: (boolean | null);
};

export type SeasonCreate = {
    name: string;
    description?: (string | null);
    league_id: string;
};

export type SeasonPublic = {
    name: string;
    description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    league_id: string;
    id: string;
};

export type SeasonsPublic = {
    data: Array<SeasonPublic>;
    count: number;
};

export type SeasonUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ClubsReadClubsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ClubsReadClubsResponse = (ClubsPublic);

export type ClubsCreateClubData = {
    requestBody: ClubCreate;
};

export type ClubsCreateClubResponse = (ClubPublic);

export type ClubsReadClubData = {
    id: string;
};

export type ClubsReadClubResponse = (ClubPublic);

export type ClubsUpdateClubData = {
    id: string;
    requestBody: ClubUpdate;
};

export type ClubsUpdateClubResponse = (ClubPublic);

export type ClubsDeleteClubData = {
    id: string;
};

export type ClubsDeleteClubResponse = (Message);

export type ClubsBulkCreateClubsData = {
    requestBody: Array<ClubCreate>;
};

export type ClubsBulkCreateClubsResponse = (Message);

export type ClubsBulkDeleteClubsData = {
    requestBody: Array<(string)>;
};

export type ClubsBulkDeleteClubsResponse = (Message);

export type LeaguesReadLeaguesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type LeaguesReadLeaguesResponse = (LeaguesPublic);

export type LeaguesCreateLeagueData = {
    requestBody: LeagueCreate;
};

export type LeaguesCreateLeagueResponse = (LeaguePublic);

export type LeaguesReadLeagueData = {
    id: string;
};

export type LeaguesReadLeagueResponse = (LeaguePublic);

export type LeaguesUpdateLeagueData = {
    id: string;
    requestBody: LeagueUpdate;
};

export type LeaguesUpdateLeagueResponse = (LeaguePublic);

export type LeaguesDeleteLeagueData = {
    id: string;
};

export type LeaguesDeleteLeagueResponse = (Message);

export type LeaguesBulkDeleteLeaguesData = {
    requestBody: Array<(string)>;
};

export type LeaguesBulkDeleteLeaguesResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MatchesReadMatchesData = {
    clubName?: (string | null);
    limit?: number;
    skip?: number;
};

export type MatchesReadMatchesResponse = (MatchesPublic);

export type MatchesUpdateMatchData = {
    matchId: string;
    requestBody: MatchUpdate;
};

export type MatchesUpdateMatchResponse = (MatchPublic);

export type MatchesDeleteMatchData = {
    matchId: string;
};

export type MatchesDeleteMatchResponse = (Message);

export type MatchesBulkDeleteMatchesData = {
    requestBody: Array<(string)>;
};

export type MatchesBulkDeleteMatchesResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SchedulersReadSchedulersData = {
    limit?: number;
    skip?: number;
};

export type SchedulersReadSchedulersResponse = (SchedulersPublic);

export type SchedulersCreateSchedulerData = {
    requestBody: SchedulerCreate;
};

export type SchedulersCreateSchedulerResponse = (SchedulerPublic);

export type SchedulersUpdateSchedulerData = {
    id: string;
    requestBody: SchedulerUpdate;
};

export type SchedulersUpdateSchedulerResponse = (SchedulerPublic);

export type SchedulersDeleteSchedulerData = {
    id: string;
};

export type SchedulersDeleteSchedulerResponse = (Message);

export type SchedulersStartSchedulerData = {
    id: string;
};

export type SchedulersStartSchedulerResponse = (SchedulerPublic);

export type SchedulersStopSchedulerData = {
    id: string;
};

export type SchedulersStopSchedulerResponse = (SchedulerPublic);

export type SeasonsReadSeasonsData = {
    leagueId?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type SeasonsReadSeasonsResponse = (SeasonsPublic);

export type SeasonsCreateSeasonData = {
    requestBody: SeasonCreate;
};

export type SeasonsCreateSeasonResponse = (SeasonPublic);

export type SeasonsUpdateSeasonData = {
    id: string;
    requestBody: SeasonUpdate;
};

export type SeasonsUpdateSeasonResponse = (SeasonPublic);

export type SeasonsDeleteSeasonData = {
    id: string;
};

export type SeasonsDeleteSeasonResponse = (Message);

export type SeasonsEndSeasonData = {
    id: string;
};

export type SeasonsEndSeasonResponse = (SeasonPublic);

export type SeasonsBulkDeleteSeasonsData = {
    requestBody: Array<(string)>;
};

export type SeasonsBulkDeleteSeasonsResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);