"""add index to matchclublink club_id

Revision ID: 1f0162f8730e
Revises: 3d257dc03cb9
Create Date: 2026-05-23 10:07:27.000604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1f0162f8730e'
down_revision = '3d257dc03cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_matchclublink_club_id', 'matchclublink', ['club_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matchclublink_club_id', table_name='matchclublink')
    # ### end Alembic commands ###
