"""Add player model

Revision ID: 231146874916
Revises: d281914b2cce
Create Date: 2026-05-17 07:44:07.870903

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '231146874916'
down_revision = 'd281914b2cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_ea_id'), table_name='player')
    op.create_index(op.f('ix_player_gamertag'), 'player', ['gamertag'], unique=False)
    op.drop_column('player', 'updated_at')
    op.drop_column('player', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_player_gamertag'), table_name='player')
    op.create_index(op.f('ix_player_ea_id'), 'player', ['ea_id'], unique=True)
    # ### end Alembic commands ###
