"""add unique constraint to club ea_id

Revision ID: 3d257dc03cb9
Revises: 93d6413690c0
Create Date: 2026-05-23 10:04:33.027256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d257dc03cb9'
down_revision = '93d6413690c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_club_ea_id', 'club', ['ea_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_club_ea_id', 'club', type_='unique')
    # ### end Alembic commands ###
