"""Add index to season league_id

Revision ID: 41bea8cdad2b
Revises: aaec815e82c9
Create Date: 2026-04-06 20:38:43.057545

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '41bea8cdad2b'
down_revision = 'aaec815e82c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_season_league_id'), 'season', ['league_id'], unique=False)
    op.drop_constraint(op.f('season_league_id_fkey'), 'season', type_='foreignkey')
    op.create_foreign_key(None, 'season', 'league', ['league_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'season', type_='foreignkey')
    op.create_foreign_key(op.f('season_league_id_fkey'), 'season', 'league', ['league_id'], ['id'])
    op.drop_index(op.f('ix_season_league_id'), table_name='season')
    # ### end Alembic commands ###
