"""add_player_stats_tables

Revision ID: 56d78761ccf7
Revises: 1f0162f8730e
Create Date: 2026-05-26 15:08:19.183876

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56d78761ccf7'
down_revision = '1f0162f8730e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playeraggregatestats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_ea_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=True),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('otl', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('game_winning_goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('possession_seconds', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('shot_attempts', sa.Integer(), nullable=False),
    sa.Column('deflections', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('pass_attempts', sa.Integer(), nullable=False),
    sa.Column('saucer_passes', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('giveaways', sa.Integer(), nullable=False),
    sa.Column('takeaways', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('blocked_shots', sa.Integer(), nullable=False),
    sa.Column('penalty_minutes', sa.Integer(), nullable=False),
    sa.Column('penalties_drawn', sa.Integer(), nullable=False),
    sa.Column('penalty_clears', sa.Integer(), nullable=False),
    sa.Column('faceoffs_won', sa.Integer(), nullable=False),
    sa.Column('faceoffs_lost', sa.Integer(), nullable=False),
    sa.Column('sum_shot_pct', sa.Float(), nullable=False),
    sa.Column('sum_shot_on_net_pct', sa.Float(), nullable=False),
    sa.Column('sum_pass_pct', sa.Float(), nullable=False),
    sa.Column('sum_fo_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_ea_id'], ['player.ea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_ea_id', 'league_id', 'season_id', name='uq_player_stats_level')
    )
    op.create_index(op.f('ix_playeraggregatestats_league_id'), 'playeraggregatestats', ['league_id'], unique=False)
    op.create_index(op.f('ix_playeraggregatestats_player_ea_id'), 'playeraggregatestats', ['player_ea_id'], unique=False)
    op.create_index(op.f('ix_playeraggregatestats_season_id'), 'playeraggregatestats', ['season_id'], unique=False)
    op.create_table('matchplayerstats',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_ea_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('loss', sa.Integer(), nullable=False),
    sa.Column('otl', sa.Integer(), nullable=False),
    sa.Column('skgoals', sa.Integer(), nullable=False),
    sa.Column('skgwg', sa.Integer(), nullable=False),
    sa.Column('skassists', sa.Integer(), nullable=False),
    sa.Column('skpossession', sa.Integer(), nullable=False),
    sa.Column('skplusmin', sa.Integer(), nullable=False),
    sa.Column('skshots', sa.Integer(), nullable=False),
    sa.Column('skshotattempts', sa.Integer(), nullable=False),
    sa.Column('skshotpct', sa.Float(), nullable=False),
    sa.Column('skshotonnetpct', sa.Float(), nullable=False),
    sa.Column('skdeflections', sa.Integer(), nullable=False),
    sa.Column('skpasses', sa.Integer(), nullable=False),
    sa.Column('skpassattempts', sa.Integer(), nullable=False),
    sa.Column('skpasspct', sa.Float(), nullable=False),
    sa.Column('sksaucerpasses', sa.Integer(), nullable=False),
    sa.Column('skhits', sa.Integer(), nullable=False),
    sa.Column('skgiveaways', sa.Integer(), nullable=False),
    sa.Column('sktakeaways', sa.Integer(), nullable=False),
    sa.Column('skinterceptions', sa.Integer(), nullable=False),
    sa.Column('skbs', sa.Integer(), nullable=False),
    sa.Column('skpim', sa.Integer(), nullable=False),
    sa.Column('skpenaltiesdrawn', sa.Integer(), nullable=False),
    sa.Column('skpkclearzone', sa.Integer(), nullable=False),
    sa.Column('skfow', sa.Integer(), nullable=False),
    sa.Column('skfol', sa.Integer(), nullable=False),
    sa.Column('skfopct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_ea_id'], ['player.ea_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'player_ea_id')
    )
    op.drop_index(op.f('ix_matchclublink_club_id'), table_name='matchclublink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_matchclublink_club_id'), 'matchclublink', ['club_id'], unique=False)
    op.drop_table('matchplayerstats')
    op.drop_index(op.f('ix_playeraggregatestats_season_id'), table_name='playeraggregatestats')
    op.drop_index(op.f('ix_playeraggregatestats_player_ea_id'), table_name='playeraggregatestats')
    op.drop_index(op.f('ix_playeraggregatestats_league_id'), table_name='playeraggregatestats')
    op.drop_table('playeraggregatestats')
    # ### end Alembic commands ###
