"""Add MatchPlayerLink model

Revision ID: 5cf3f39e8bab
Revises: 231146874916
Create Date: 2026-05-18 13:38:48.678104

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5cf3f39e8bab'
down_revision = '231146874916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchplayerlink',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_ea_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_ea_id'], ['player.ea_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'player_ea_id')
    )
    op.create_index('ix_matchplayerlink_player_ea_id', 'matchplayerlink', ['player_ea_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matchplayerlink_player_ea_id', table_name='matchplayerlink')
    op.drop_table('matchplayerlink')
    # ### end Alembic commands ###
