"""add_indexes_to_club

Revision ID: a16f2e6acc13
Revises: bddefa5e844e
Create Date: 2026-04-07 22:59:42.823036

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a16f2e6acc13'
down_revision = 'bddefa5e844e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
