"""Add scheduler and match models

Revision ID: aec30638b4db
Revises: a16f2e6acc13
Create Date: 2026-04-09 20:35:00.298204

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aec30638b4db'
down_revision = 'a16f2e6acc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_match_league_id'), 'match', ['league_id'], unique=False)
    op.create_index(op.f('ix_match_season_id'), 'match', ['season_id'], unique=False)
    op.create_table('scheduler',
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season_id', name='uq_scheduler_league_season')
    )
    op.create_index(op.f('ix_scheduler_league_id'), 'scheduler', ['league_id'], unique=False)
    op.create_index(op.f('ix_scheduler_season_id'), 'scheduler', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_season_id'), table_name='scheduler')
    op.drop_index(op.f('ix_scheduler_league_id'), table_name='scheduler')
    op.drop_table('scheduler')
    op.drop_index(op.f('ix_match_season_id'), table_name='match')
    op.drop_index(op.f('ix_match_league_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
