"""add unique constraint to club name

Revision ID: b0d0df7ae555
Revises: f96c0fe9eb0b
Create Date: 2026-04-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b0d0df7ae555'
down_revision = 'f96c0fe9eb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_club_name', table_name='club')
    op.create_index(op.f('ix_club_name'), 'club', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_name'), table_name='club')
    op.create_index('ix_club_name', 'club', ['name'], unique=False)
    # ### end Alembic commands ###
