"""add club season and league relationships

Revision ID: bddefa5e844e
Revises: 51e851130dcc
Create Date: 2026-04-07 20:44:30.301071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bddefa5e844e'
down_revision = '51e851130dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubleaguelink',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', 'league_id')
    )
    op.create_table('clubseasonlink',
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', 'season_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubseasonlink')
    op.drop_table('clubleaguelink')
    # ### end Alembic commands ###
