"""add unsaved_match and scheduler_activity models

Revision ID: d281914b2cce
Revises: b0d0df7ae555
Create Date: 2026-05-10 12:09:50.603553

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd281914b2cce'
down_revision = 'b0d0df7ae555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduleractivity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheduler_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduleractivity_scheduler_id'), 'scheduleractivity', ['scheduler_id'], unique=False)
    op.create_table('unsavedmatch',
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('scheduler_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_unsavedmatch_league_id'), 'unsavedmatch', ['league_id'], unique=False)
    op.create_index(op.f('ix_unsavedmatch_scheduler_id'), 'unsavedmatch', ['scheduler_id'], unique=False)
    op.create_index(op.f('ix_unsavedmatch_season_id'), 'unsavedmatch', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unsavedmatch_season_id'), table_name='unsavedmatch')
    op.drop_index(op.f('ix_unsavedmatch_scheduler_id'), table_name='unsavedmatch')
    op.drop_index(op.f('ix_unsavedmatch_league_id'), table_name='unsavedmatch')
    op.drop_table('unsavedmatch')
    op.drop_index(op.f('ix_scheduleractivity_scheduler_id'), table_name='scheduleractivity')
    op.drop_table('scheduleractivity')
    # ### end Alembic commands ###
