"""add last_run_status to scheduler

Revision ID: f96c0fe9eb0b
Revises: aec30638b4db
Create Date: 2026-04-23 20:30:59.703293

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f96c0fe9eb0b'
down_revision = 'aec30638b4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler', sa.Column('last_run_status', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler', 'last_run_status')
    # ### end Alembic commands ###
