/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutXbhlRouteImport } from './routes/_layout/xbhl'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutXbhlIndexRouteImport } from './routes/_layout/xbhl/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutAdminSchedulersRouteImport } from './routes/_layout/admin/schedulers'
import { Route as LayoutAdminMatchesRouteImport } from './routes/_layout/admin/matches'
import { Route as LayoutAdminClubsRouteImport } from './routes/_layout/admin/clubs'
import { Route as LayoutXbhlLeagueIdIndexRouteImport } from './routes/_layout/xbhl/$leagueId.index'
import { Route as LayoutXbhlLeagueIdSeasonIdRouteImport } from './routes/_layout/xbhl/$leagueId.$seasonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutXbhlRoute = LayoutXbhlRouteImport.update({
  id: '/xbhl',
  path: '/xbhl',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutXbhlIndexRoute = LayoutXbhlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutXbhlRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSchedulersRoute = LayoutAdminSchedulersRouteImport.update({
  id: '/schedulers',
  path: '/schedulers',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminMatchesRoute = LayoutAdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminClubsRoute = LayoutAdminClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutXbhlLeagueIdIndexRoute = LayoutXbhlLeagueIdIndexRouteImport.update({
  id: '/$leagueId/',
  path: '/$leagueId/',
  getParentRoute: () => LayoutXbhlRoute,
} as any)
const LayoutXbhlLeagueIdSeasonIdRoute =
  LayoutXbhlLeagueIdSeasonIdRouteImport.update({
    id: '/$leagueId/$seasonId',
    path: '/$leagueId/$seasonId',
    getParentRoute: () => LayoutXbhlRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/xbhl': typeof LayoutXbhlRouteWithChildren
  '/admin/clubs': typeof LayoutAdminClubsRoute
  '/admin/matches': typeof LayoutAdminMatchesRoute
  '/admin/schedulers': typeof LayoutAdminSchedulersRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/xbhl/': typeof LayoutXbhlIndexRoute
  '/xbhl/$leagueId/$seasonId': typeof LayoutXbhlLeagueIdSeasonIdRoute
  '/xbhl/$leagueId/': typeof LayoutXbhlLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/clubs': typeof LayoutAdminClubsRoute
  '/admin/matches': typeof LayoutAdminMatchesRoute
  '/admin/schedulers': typeof LayoutAdminSchedulersRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/xbhl': typeof LayoutXbhlIndexRoute
  '/xbhl/$leagueId/$seasonId': typeof LayoutXbhlLeagueIdSeasonIdRoute
  '/xbhl/$leagueId': typeof LayoutXbhlLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/xbhl': typeof LayoutXbhlRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/clubs': typeof LayoutAdminClubsRoute
  '/_layout/admin/matches': typeof LayoutAdminMatchesRoute
  '/_layout/admin/schedulers': typeof LayoutAdminSchedulersRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/xbhl/': typeof LayoutXbhlIndexRoute
  '/_layout/xbhl/$leagueId/$seasonId': typeof LayoutXbhlLeagueIdSeasonIdRoute
  '/_layout/xbhl/$leagueId/': typeof LayoutXbhlLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/xbhl'
    | '/admin/clubs'
    | '/admin/matches'
    | '/admin/schedulers'
    | '/admin/'
    | '/xbhl/'
    | '/xbhl/$leagueId/$seasonId'
    | '/xbhl/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/settings'
    | '/'
    | '/admin/clubs'
    | '/admin/matches'
    | '/admin/schedulers'
    | '/admin'
    | '/xbhl'
    | '/xbhl/$leagueId/$seasonId'
    | '/xbhl/$leagueId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/xbhl'
    | '/_layout/'
    | '/_layout/admin/clubs'
    | '/_layout/admin/matches'
    | '/_layout/admin/schedulers'
    | '/_layout/admin/'
    | '/_layout/xbhl/'
    | '/_layout/xbhl/$leagueId/$seasonId'
    | '/_layout/xbhl/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/xbhl': {
      id: '/_layout/xbhl'
      path: '/xbhl'
      fullPath: '/xbhl'
      preLoaderRoute: typeof LayoutXbhlRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/xbhl/': {
      id: '/_layout/xbhl/'
      path: '/'
      fullPath: '/xbhl/'
      preLoaderRoute: typeof LayoutXbhlIndexRouteImport
      parentRoute: typeof LayoutXbhlRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/schedulers': {
      id: '/_layout/admin/schedulers'
      path: '/schedulers'
      fullPath: '/admin/schedulers'
      preLoaderRoute: typeof LayoutAdminSchedulersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/matches': {
      id: '/_layout/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof LayoutAdminMatchesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/clubs': {
      id: '/_layout/admin/clubs'
      path: '/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof LayoutAdminClubsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/xbhl/$leagueId/': {
      id: '/_layout/xbhl/$leagueId/'
      path: '/$leagueId'
      fullPath: '/xbhl/$leagueId/'
      preLoaderRoute: typeof LayoutXbhlLeagueIdIndexRouteImport
      parentRoute: typeof LayoutXbhlRoute
    }
    '/_layout/xbhl/$leagueId/$seasonId': {
      id: '/_layout/xbhl/$leagueId/$seasonId'
      path: '/$leagueId/$seasonId'
      fullPath: '/xbhl/$leagueId/$seasonId'
      preLoaderRoute: typeof LayoutXbhlLeagueIdSeasonIdRouteImport
      parentRoute: typeof LayoutXbhlRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminClubsRoute: typeof LayoutAdminClubsRoute
  LayoutAdminMatchesRoute: typeof LayoutAdminMatchesRoute
  LayoutAdminSchedulersRoute: typeof LayoutAdminSchedulersRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminClubsRoute: LayoutAdminClubsRoute,
  LayoutAdminMatchesRoute: LayoutAdminMatchesRoute,
  LayoutAdminSchedulersRoute: LayoutAdminSchedulersRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutXbhlRouteChildren {
  LayoutXbhlIndexRoute: typeof LayoutXbhlIndexRoute
  LayoutXbhlLeagueIdSeasonIdRoute: typeof LayoutXbhlLeagueIdSeasonIdRoute
  LayoutXbhlLeagueIdIndexRoute: typeof LayoutXbhlLeagueIdIndexRoute
}

const LayoutXbhlRouteChildren: LayoutXbhlRouteChildren = {
  LayoutXbhlIndexRoute: LayoutXbhlIndexRoute,
  LayoutXbhlLeagueIdSeasonIdRoute: LayoutXbhlLeagueIdSeasonIdRoute,
  LayoutXbhlLeagueIdIndexRoute: LayoutXbhlLeagueIdIndexRoute,
}

const LayoutXbhlRouteWithChildren = LayoutXbhlRoute._addFileChildren(
  LayoutXbhlRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutXbhlRoute: typeof LayoutXbhlRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutXbhlRoute: LayoutXbhlRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
